### ISSUE TITLE
Did you have this error msg when importing project in AS?

### ISSUE THREAD

**Issue by bainian** [tommykw/Musical#2]
when import project in my AS, gradle compiled with error:

Error:Execution failed for task ':mylibrary:transformResourcesWithMergeJavaResForRelease'.

> com.android.build.api.transform.TransformException: com.android.builder.packaging.DuplicateFileException: Duplicate files copied in APK META-INF/DEPENDENCIES
>     File1: /home/sage/Documents/android/CoolMusicPlayer/mylibrary/libs/httpcore-4.4.3.jar
>     File2: /home/sage/Documents/android/CoolMusicPlayer/mylibrary/libs/httpclient-4.5.1.jar

did you run into this error in import project in AS? any solution with you? thanks.

ps, this project looks like cool, I will keep attention with it.

**Comment by tommykw** [comment]
I'm really sorry to be late.
My environment was not a problem in the AS2.1 beta2.

What's your version?
